spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_photo_blog
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: 2021
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
logging:
    level:
      liquibase: INFO
management:
  server:
    port: 7777
  security:
    enabled: true
  endpoints:
    actuator:
      enabled: true
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
    enabled-by-defaults: true
