management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  info:
    git:
      mode: full

info:
  version: @project.version@
  author: dkogan
  descriptiion: THis is SPring Bot example

